### ISSUE TITLE
[Bug] 未知bug

### ISSUE THREAD

**Issue by furryaxw** [ChatLunaLab/chatluna-character#8]
chatluna beta 119
chatluna-character 0.0.75
初次加载时：
app TypeError: Cannot read properties of undefined (reading 'split')
                            at parseRawModelName (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/utils/count_tokens.cjs:233:20)
                            at apply (/koishi/node_modules/koishi-plugin-chatluna-character/lib/index.cjs:53:75)
                            at plugins (/koishi/node_modules/koishi-plugin-chatluna-character/lib/index.cjs:682:11)
                            at Object.apply (/koishi/node_modules/koishi-plugin-chatluna-character/lib/index.cjs:1178:15)
                            at async Promise.all (index 3)
                            at async Proxy.flush (/koishi/node_modules/@cordisjs/core/lib/index.cjs:497:7)
                            at async Proxy.start (/koishi/node_modules/@cordisjs/core/lib/index.cjs:571:5)
                            at async start (/koishi/node_modules/koishi/lib/worker/index.js:146:3)

重载后为：
app TypeError: Cannot read properties of undefined (reading 'split')
                            at parseRawModelName (/koishi/node_modules/koishi-plugin-chatluna/lib/llm-core/utils/count_tokens.cjs:233:20)
                            at apply (/koishi/node_modules/koishi-plugin-chatluna-character/lib/index.cjs:53:75)
                            at plugins (/koishi/node_modules/koishi-plugin-chatluna-character/lib/index.cjs:682:11)
                            at Object.apply (/koishi/node_modules/koishi-plugin-chatluna-character/lib/index.cjs:1178:15)

**Comment by dingyi222666** [comment]
选择其他的伪装可用模型，然后选回来。
